name: env-vars-example
on:
  push:
env:
  VENI: 'I came'
jobs:
  use-env-vars:
    runs-on: ubuntu-latest
    env:
      VIDI: 'I saw'
    steps:
      -
        name: Show me the vars
        run: echo "$VENI, $VIDI, $VICI"
        env:
          VICI: 'I conquered'
      -
        name: Create env var
        run: echo "foo=bar" >> ${{ github.env }}
      -
        name: Useful default vars
        run: |
          echo "Workflow name:  ${{ github.workflow }}"
          echo "Workspace:      ${{ github.workspace }}"
          echo "Event:          ${{ github.event_name }}"
          echo "SHA:            ${{ github.sha }}"
          echo "Ref:            ${{ github.ref }}"
