name: event-triggers-example
on:
  push:
    branches:
      - 'foo'
  pull_request:
    branches:
      - 'develop'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Event
        run: echo "Triggered by ${{ github.event_name }}"
      -
        name: Say Hello
        run: echo "Hello world!"
