name: job-matrix
on:
  push:
    branches:
      - 'foo'

jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node: [18, 20, 22]
        exclude:
          -
            os: ubuntu-16.04
            node: 18
        include:
          -
            os: macos-latest
            node: 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      -
        name: Run script from repo
        run: node helloworld.js
